variable "github_token" {

}

variable "issue_labels" {
  default = {
    "DE.AE - Anomalies and Events" = "71767a"
    "DE.CM - Security Continuous Monitoring" = "71767a"
    "DE.DP- Detection Processes" = "71767a"
    "ID.AM - Asset Management" = "71767a"
    "ID.BE - Business Environment" = "71767a"
    "ID.GV - Governance" = "71767a"
    "ID.RA - Risk Assessment" = "71767a"
    "ID.RM - Risk Management Strategy" = "71767a"
    "ID.SC - Supply Chain Risk Management" = "71767a"
    "ID.SC - Supply Chain Risk Management" = "71767a"
    "PR.AC - Identity Management and Access Control" = "71767a"
    "PR.AT - Awareness and Training" = "71767a"
    "PR.DS - Data Security" = "71767a"
    "PR.IP - Information Protection ProcessesProcedures" = "71767a"
    "PR.MA - Maintenance" = "71767a"
    "PR.PT - Protective Technology" = "71767a"
    "RC.CO - Communications" = "71767a"
    "RC.IM - Recovery Improvements" = "71767a"
    "RC.RP - Recovery Planning" = "71767a"
    "RS.AN - Analysis" = "71767a"
    "RS.IM - Response Improvements" = "71767a"
    "RS.MI - Mitigation" = "71767a"
    "RS.RP - Response Planning" = "71767a"
    "Epic" = "000000"
    "groomed - accepted" = "d5bfff"
    "groomed - needs acceptance" = "e2bee4"
    "needs grooming" = "d0c3e9"
    "Epic-able" = "446443"
    "Sprint Consideration" = "28a0cb"
    "Passion Project" = "ecbec6"
    "Expedite" = "a9f9e5"
    "prep step" = "ecc0a7"
    "staffing request-able" = "008672"
    "size: days" = "dec69a"
    "size: hours" = "ffbe2e"
    "size:  months" = "face00"
    "size: weeks" = "e6c74c"
    "blog-able" = "f0bbcc"
    "demo-able" = "ffb4cf"
    "Feedback Needed" = "c6cace"
    "epic: acquisition/procurement" = "70e17b"
    "epic: alerting" = "b4d0b9"
    "epic: ATO Improvements" = "bbcae4"
    "epic: authorization" = "cbd17a"
    "epic: better sharing" = "aacdec"
    "epic: cloud service inventory management" = "bbc8f5"
    "epic: customer service" = "29e1cb"
    "epic: data" = "cbd17a"
    "epic: documentation" = "b8d293"
    "epic: domain name management" = "92d9bb"
    "epic: github management" = "b7caf0"
    "epic: infrastructure management" = "9ddfeb"
    "epic: internal workflow/procedures" = "52daf2"
    "epic: secret management" = "0ceda6"
    "epic: security automation" = "9bd4cf"
    "epic: security Maturity" = "adcfdc"
    "epic: software" = "c5d30a"
    "epic: vulnerability management" = "97d4ea"
}
}
