variable "github_token" {

}

variable "issue_labels" {
  default = {
    "DE.AE - Anomalies and Events"                       = "FFFFFF"
    "DE.CM - Security Continuous Monitoring"             = "FFFFFF"
    "DE.DP- Detection Processes"                         = "FFFFFF"
    "ID.AM - Asset Management"                           = "FFFFFF"
    "ID.BE - Business Environment"                       = "FFFFFF"
    "ID.GV - Governance"                                 = "FFFFFF"
    "ID.RA - Risk Assessment"                            = "FFFFFF"
    "ID.RM - Risk Management Strategy"                   = "FFFFFF"
    "ID.SC - Supply Chain Risk Management"               = "FFFFFF"
    "PR.AC - Identity Management and Access Control"     = "FFFFFF"
    "PR.AT - Awareness and Training"                     = "FFFFFF"
    "PR.DS - Data Security"                              = "FFFFFF"
    "PR.IP - Information Protection ProcessesProcedures" = "FFFFFF"
    "PR.MA - Maintenance"                                = "FFFFFF"
    "PR.PT - Protective Technology"                      = "FFFFFF"
    "RC.CO - Communications"                             = "FFFFFF"
    "RC.IM - Recovery Improvements"                      = "FFFFFF"
    "RC.RP - Recovery Planning"                          = "FFFFFF"
    "RS.AN - Analysis"                                   = "FFFFFF"
    "RS.IM - Response Improvements"                      = "FFFFFF"
    "RS.MI - Mitigation"                                 = "FFFFFF"
    "RS.RP - Response Planning"                          = "FFFFFF"
    "groomed: delegate"                                  = "d5bfff"
    "groomed: decide"                                    = "d5bfff"
    "groomed: accepted"                                  = "d5bfff"
    "groomed: draft - final"                             = "d5bfff"
    "grooming: draft - initial"                          = "d5bfff"
    "grooming: team"                                     = "d5bfff"
    "sprint: planning"                                   = "a6b557"
    "sprint: review"                                     = "a6b557"
    "passion project"                                    = "afaea2"
    "internal workflow"                                  = "afaea2"
    "documentation"                                      = "fc906d"
    "prep step"                                          = "fc906d"
    "size: days"                                         = "dec69a"
    "size: hours"                                        = "dec69a"
    "size: months"                                       = "dec69a"
    "size: weeks"                                        = "dec69a"
    "due date"                                           = "e9695f"
    "feedback needed"                                    = "e9695f"
    "expedite"                                           = "e9695f"
    "blog-able"                                          = "c9ab48"
    "demo-able"                                          = "c9ab48"
    "epic: security and compliance"                      = "6ecbdb"
    "epic: software and infrastructure"                  = "6ecbdb"
    "epic: policy and guidance"                          = "6ecbdb"
    "epic: acquisition procurement and budgeting"        = "6ecbdb"
    "epic: customer service and communication"           = "6ecbdb"
    "epic: dogfood-ing"                                  = "6ecbdb"
     "sprint: new"                          = "a6b557"
  }
}
