version: 2.1
orbs:
  node: circleci/node@4.0.0
workflows:
  node-tests:
    jobs:
      - node/test:
          app-dir: inspector
        environment:
          TRELLO_KEY: test_key
          TRELLO_TOKEN: test_token
