version: 2.1
orbs:
  node: circleci/node@4.0.0
  terraform: circleci/terraform@2.0.0
workflows:
  node-tests:
    jobs:
      - node/test:
          app-dir: inspector
      - run:
          name: Lint JavaScript
          command: npm run lint
  terraform:
    jobs:
      - terraform/validate:
          backend: false
          checkout: true
          path: terraform/
