version: 2.1
orbs:
  node: circleci/node@4.0.0
  terraform: circleci/terraform@2.1.0
workflows:
  node-tests:
    jobs:
      - node/test:
          app-dir: inspector
  terraform:
    jobs:
      - terraform/validate:
          backend: false
          checkout: true
          path: terraform/
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: master
          requires:
            - terraform/plan
