name: Monthly
on:
  push: # testing
  schedule:
    - cron: 0 6 15 * *

jobs:
  create_issue:
    name: Create invoice issue for COR
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      # https://stackoverflow.com/a/60942437/358804
      - name: Get dates
        id: date
        run: |
          echo "::set-output name=current::$(date +'%m/%y')"
          echo "::set-output name=due::$(date -d '+15 days' +'%m/%d/%y')"
      - name: Create issue
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: jjediny
          labels: "g: accepted, m: due date, i: SaaS"
          title: process invoices for ${{ steps.date.outputs.current }} - due ${{ steps.date.outputs.due }}
          body: |
            ### Implementation steps

            Confirm usage and route invoices to Contracting Officer (CO) for:

            - [ ] AWS
            - [ ] Azure
            - [ ] GCP
            - [ ] HackerOne
            - [ ] Mural
            - [ ] New Relic
                    
            ### Acceptance criteria
            
            - [ ] All invoices routed
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
